name: e2e-presidio-evaluation-pipeline

on:
  workflow_dispatch:
jobs:
  set-env-branch:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: set-prod-branch
        if: ${{ github.ref == 'refs/heads/main'}}
        run: echo "config_env=config-infra-prod.yml" >> $GITHUB_ENV;
      - id: set-dev-branch
        name: setdevbranch
        if: ${{ github.ref != 'refs/heads/main'}}
        run: echo "config_env=config-infra-dev.yml" >> $GITHUB_ENV;
      - id: set-output-defaults
        name: set-output-defaults
        run: |
          echo "config-file=$config_env" >> $GITHUB_OUTPUT;
  get-config:
    needs: set-env-branch
    uses: Azure/mlops-templates/.github/workflows/read-yaml.yml@main
    with:
      file_name: ${{ needs.set-env-branch.outputs.config-file}}
  register-environment:
    needs: [get-config]
    uses: Azure/mlops-templates/.github/workflows/register-environment.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      environment_file: mlops/environments/evaluation-env.yml
      conda_file: data-science/environment/eval-conda.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  create-compute:
    needs: [get-config]
    uses: Azure/mlops-templates/.github/workflows/create-compute.yml@main
    with:
      cluster_name: cpu-cluster
      size: Standard_DS3_v2
      min_instances: 0
      max_instances: 4
      cluster_tier: low_priority
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  register-raw-dataset:
    needs: [get-config]
    uses: Azure/mlops-templates/.github/workflows/register-dataset.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      name: evaluation-data
      data_file: mlops/data/data.yml
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  run-data-augmented-pipeline:
    needs: [get-config, register-raw-dataset]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/augement_data_pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  run-evaluation-raw-data-pipeline:
    needs: [get-config, register-raw-dataset]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/evaluation_pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
  run-evaluation-augmented-data-pipeline:
    needs: [get-config, run-data-augmented-pipeline]
    uses: Azure/mlops-templates/.github/workflows/run-pipeline.yml@main
    with:
      resource_group: ${{ needs.get-config.outputs.resource_group }}
      workspace_name: ${{ needs.get-config.outputs.aml_workspace }}
      parameters-file: mlops/evaluation_augmented_pipeline.yml
      job-name: test
    secrets:
      creds: ${{secrets.AZURE_CREDENTIALS}}
